
WITH F AS (
  SELECT CAR_ID, START_DATE
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
  WHERE START_DATE >= '2022-08-01'
    AND START_DATE <  '2022-11-01'
),
C AS (
  SELECT CAR_ID
  FROM F
  GROUP BY CAR_ID
  HAVING COUNT(*) >= 5
)
SELECT
  MONTH(f.START_DATE) AS MONTH,
  f.CAR_ID,
  COUNT(*) AS RECORDS
FROM F f
JOIN C c ON c.CAR_ID = f.CAR_ID
GROUP BY MONTH(f.START_DATE), f.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;
